export const instruments = [
  {
    instrumentName: "M02",
    FCID: "AA1234567-ABB",
    currentCycle: 11,
    totalCycle: 115,
    backW: true,
    instrumentStatus: "operational",
    instrumentType: "George",
    IDITnumber: "NA",
    startTime: "2020-05-15T08:03:11",
    cycleLength: 3,
  },
  {
    instrumentName: "M04",
    FCID: "AA1234567-ABB",
    currentCycle: 115,
    totalCycle: 125,
    backW: false,
    instrumentStatus: "operational",
    instrumentType: "George",
    IDITnumber: "NA",
    startTime: "2020-05-15T08:17:53",
    cycleLength: 3,
  },
  {
    instrumentName: "M05",
    FCID: "AA1234567-ABB",
    currentCycle: 138,
    totalCycle: 175,
    backW: true,
    instrumentStatus: "operational",
    instrumentType: "George",
    IDITnumber: "NA",
    startTime: "2020-05-15T09:41:25",
    cycleLength: 3,
  },
  {
    instrumentName: "B01",
    FCID: "AA1234567-ABB",
    currentCycle: 34,
    totalCycle: 52,
    backW: true,
    instrumentStatus: "validation needed",
    instrumentType: "Barracuda",
    IDITnumber: "IDIT-1605",
    startTime: "2020-05-15T07:31:00",
    cycleLength: 5,
  },
  {
    instrumentName: "B02",
    FCID: "AA1234567-ABB",
    currentCycle: 173,
    totalCycle: 215,
    backW: true,
    instrumentStatus: "operational",
    instrumentType: "Barracuda",
    IDITnumber: "NA",
    startTime: "2020-05-15T08:24:25",
    cycleLength: 5,
  },
  {
    instrumentName: "B07",
    FCID: "NA",
    currentCycle: "NA",
    totalCycle: "NA",
    backW: "NA",
    instrumentStatus: "down",
    instrumentType: "Barracuda",
    IDITnumber: "IDIT-1618",
    startTime: "NA",
    cycleLength: "NA",
  },
  {
    instrumentName: "B13",
    FCID: "NA",
    currentCycle: "NA",
    totalCycle: "NA",
    backW: "NA",
    instrumentStatus: "out of lab",
    instrumentType: "Barracuda",
    IDITnumber: "IDIT-1630",
    startTime: "NA",
    cycleLength: "NA",
  },
  {
    instrumentName: "B09",
    FCID: "AA1234567-ABB",
    currentCycle: 10,
    totalCycle: 175,
    backW: false,
    instrumentStatus: "operational",
    instrumentType: "Barracuda",
    IDITnumber: "NA",
    startTime: "2020-05-15T07:49:16",
    cycleLength: 5,
  },
  {
    instrumentName: "B08",
    FCID: "AA1234567-ABB",
    currentCycle: 32,
    totalCycle: 75,
    backW: true,
    instrumentStatus: "validation needed",
    instrumentType: "Barracuda",
    IDITnumber: "IDIT-1613",
    startTime: "2020-05-15T10:12:57",
    cycleLength: 7,
  },
  {
    instrumentName: "B03",
    FCID: "AA1234567-ABB",
    currentCycle: 93,
    totalCycle: 215,
    backW: true,
    instrumentStatus: "operational",
    instrumentType: "Barracuda",
    IDITnumber: "NA",
    startTime: "2020-05-15T07:17:59",
    cycleLength: 5,
  },
  {
    instrumentName: "B06",
    FCID: "AA1234567-ABB",
    currentCycle: 62,
    totalCycle: 175,
    backW: false,
    instrumentStatus: "operational",
    instrumentType: "Barracuda",
    IDITnumber: "NA",
    startTime: "2020-05-15T12:31:53",
    cycleLength: 5,
  },
];
